[package]
name = "plantoid-caretaker"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8.0"
bevy_mod_raycast = "0.6.0"

[target.'cfg(target_arch = "wasm32")'.dependencies] 
bevy = {version = "0.8.0", default-features = false}
